/** @type {import('../types/room').Room[]} */
export const mockRooms = [
    {
        id: 1,
        name: "Deluxe City View",
        pricePerNight: 129.0,
        imageUrl: "https://besthotelshome.com/wp-content/uploads/2020/11/Top-10-best-luxury-5-star-hotels-in-Ho-Chi-Minh-City-Vietnam.jpg",
        beds: 1,
        capacity: 2,
        rating: 4.5,
        shortDesc: "1 giường · 2 khách, view thành phố, bữa sáng ngon",
        status: "Available",
    },
    {
        id: 2,
        name: "Family Suite",
        pricePerNight: 199.0,
        imageUrl: "https://trv-checkin.s3-eu-central-1.amazonaws.com/wp-content/uploads/sites/14/2015/10/Corinthia-room.jpg",
        beds: 2,
        capacity: 4,
        rating: 4.7,
        shortDesc: "2 giường · 4 khách, căn góc rộng, gần trung tâm",
        status: "Available",
    },
    {
        id: 3,
        name: "Radisson Hotel",
        pricePerNight: 89.0,
        imageUrl: "https://www.vietnamonline.com/media/uploads/froala_editor/images/VNO_Citadines%20Bayfront%20Nha%20Trang.png",
        beds: 1,
        capacity: 2,
        rating: 4.2,
        shortDesc: "1 giường · 2 khách, hồ bơi ngoài trời, spa thư giãn",
        status: "Available",
    },
    {
        id: 4,
        name: "Twin Business",
        pricePerNight: 109.0,
        imageUrl: "",
        beds: 2,
        capacity: 2,
        rating: 4.1,
        shortDesc: "2 giường · 2 khách, phù hợp công tác, gần khu tài chính",
        status: "Available",
    },
    {
        id: 5,
        name: "Bali Resort",
        pricePerNight: 259.0,
        imageUrl: "https://simply-madeleine.com/wp-content/uploads/2024/01/Pangulasian-Island-Pool-Dinner.jpg",
        beds: 1,
        capacity: 3,
        rating: 4.9,
        shortDesc: "1 giường · 3 khách, view biển, đồ ăn ngon, bar bãi biển",
        status: "Available",
    },
    {
        id: 6,
        name: "Ocean View Suite",
        pricePerNight: 59.0,
        imageUrl: "https://i.pinimg.com/originals/e9/38/53/e93853b0add8b85dda930dfde059c7f9.jpg",
        beds: 1,
        capacity: 2,
        rating: 3.9,
        shortDesc: "1 giường · 2 khách, ban công hướng biển, gần chợ đêm",
        status: "Available",
    },
];